// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuneBot.Specs.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BiddingPhaseFeature : object, Xunit.IClassFixture<BiddingPhaseFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "BiddingPhase.feature"
#line hidden
        
        public BiddingPhaseFeature(BiddingPhaseFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Bidding Phase", "    As a Dune player\n    I want to bid on Treachery Cards\n    So that I can gain " +
                    "advantages and weapons", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("a game with 4 factions: Atreides, Harkonnen, Emperor, Fremen", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("the game is in the \"Bidding\" phase", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Players with full hands are excluded from dealing count")]
        [Xunit.TraitAttribute("FeatureTitle", "Bidding Phase")]
        [Xunit.TraitAttribute("Description", "Players with full hands are excluded from dealing count")]
        public async System.Threading.Tasks.Task PlayersWithFullHandsAreExcludedFromDealingCount()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Players with full hands are excluded from dealing count", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 11
    await testRunner.GivenAsync("\"Atreides\" has 4 Treachery Cards", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
    await testRunner.AndAsync("\"Harkonnen\" has 1 Treachery Card", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
    await testRunner.AndAsync("\"Emperor\" has 0 Treachery Cards", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.AndAsync("\"Fremen\" has 3 Treachery Cards", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.WhenAsync("the Bidding Phase starts", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("3 cards should be dealt for auction", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Players with full hands cannot bid")]
        [Xunit.TraitAttribute("FeatureTitle", "Bidding Phase")]
        [Xunit.TraitAttribute("Description", "Players with full hands cannot bid")]
        public async System.Threading.Tasks.Task PlayersWithFullHandsCannotBid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Players with full hands cannot bid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.GivenAsync("\"Atreides\" has 4 Treachery Cards", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.AndAsync("\"Harkonnen\" has 0 Treachery Cards", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.WhenAsync("the Bidding Phase starts", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("\"Atreides\" should not be eligible to bid", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
    await testRunner.AndAsync("\"Harkonnen\" should be eligible to bid", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="First player starts bidding")]
        [Xunit.TraitAttribute("FeatureTitle", "Bidding Phase")]
        [Xunit.TraitAttribute("Description", "First player starts bidding")]
        public async System.Threading.Tasks.Task FirstPlayerStartsBidding()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("First player starts bidding", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.GivenAsync("\"Atreides\" is the First Player", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
    await testRunner.AndAsync("all players have 0 Treachery Cards", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
    await testRunner.WhenAsync("the Bidding Phase starts", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("it should be \"Atreides\" turn to bid", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Bidding must exceed current bid")]
        [Xunit.TraitAttribute("FeatureTitle", "Bidding Phase")]
        [Xunit.TraitAttribute("Description", "Bidding must exceed current bid")]
        public async System.Threading.Tasks.Task BiddingMustExceedCurrentBid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Bidding must exceed current bid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 32
    await testRunner.GivenAsync("\"Atreides\" is the First Player", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 33
    await testRunner.AndAsync("the current bid is 2", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.WhenAsync("\"Atreides\" places a bid of 1", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
    await testRunner.ThenAsync("the bid should be rejected", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Bidding cannot exceed spice holdings")]
        [Xunit.TraitAttribute("FeatureTitle", "Bidding Phase")]
        [Xunit.TraitAttribute("Description", "Bidding cannot exceed spice holdings")]
        public async System.Threading.Tasks.Task BiddingCannotExceedSpiceHoldings()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Bidding cannot exceed spice holdings", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 38
    await testRunner.GivenAsync("\"Atreides\" is the First Player", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
    await testRunner.AndAsync("\"Atreides\" has 5 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.WhenAsync("\"Atreides\" places a bid of 6", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
    await testRunner.ThenAsync("the bid should be rejected", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Basic Auction Flow")]
        [Xunit.TraitAttribute("FeatureTitle", "Bidding Phase")]
        [Xunit.TraitAttribute("Description", "Basic Auction Flow")]
        public async System.Threading.Tasks.Task BasicAuctionFlow()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Basic Auction Flow", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 44
    await testRunner.GivenAsync("\"Atreides\" is the First Player", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
    await testRunner.AndAsync("\"Harkonnen\" is second", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
    await testRunner.AndAsync("\"Emperor\" is third", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
    await testRunner.AndAsync("\"Atreides\" has 10 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.AndAsync("\"Harkonnen\" has 10 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
    await testRunner.WhenAsync("the Bidding Phase starts", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
    await testRunner.AndAsync("\"Atreides\" places a bid of 1", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.ThenAsync("the current bid should be 1", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 52
    await testRunner.AndAsync("high bidder should be \"Atreides\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
    await testRunner.AndAsync("it should be \"Harkonnen\" turn to bid", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Passing rotates strictly to next player")]
        [Xunit.TraitAttribute("FeatureTitle", "Bidding Phase")]
        [Xunit.TraitAttribute("Description", "Passing rotates strictly to next player")]
        public async System.Threading.Tasks.Task PassingRotatesStrictlyToNextPlayer()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Passing rotates strictly to next player", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 56
    await testRunner.GivenAsync("\"Atreides\" is first", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 57
    await testRunner.AndAsync("\"Harkonnen\" is second", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
    await testRunner.AndAsync("\"Emperor\" is third", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.WhenAsync("the Bidding Phase starts", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
    await testRunner.AndAsync("\"Atreides\" passes", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.ThenAsync("it should be \"Harkonnen\" turn to bid", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Winning a bid")]
        [Xunit.TraitAttribute("FeatureTitle", "Bidding Phase")]
        [Xunit.TraitAttribute("Description", "Winning a bid")]
        public async System.Threading.Tasks.Task WinningABid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Winning a bid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 64
    await testRunner.GivenAsync("\"Atreides\" is first", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 65
    await testRunner.AndAsync("\"Harkonnen\" is second", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
    await testRunner.AndAsync("\"Emperor\" is third", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
    await testRunner.AndAsync("\"Atreides\" has 10 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
    await testRunner.AndAsync("\"Emperor\" has 10 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
    await testRunner.WhenAsync("the Bidding Phase starts", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
    await testRunner.AndAsync("\"Atreides\" places a bid of 2", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
    await testRunner.AndAsync("\"Harkonnen\" passes", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
    await testRunner.AndAsync("\"Emperor\" passes", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
    await testRunner.AndAsync("\"Fremen\" passes", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
    await testRunner.ThenAsync("\"Atreides\" should win the auction", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 75
    await testRunner.AndAsync("\"Atreides\" should have 8 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
    await testRunner.AndAsync("\"Emperor\" should have 12 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
    await testRunner.AndAsync("\"Atreides\" should have 1 Treachery Cards", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Next card starts with player to the right of previous starter")]
        [Xunit.TraitAttribute("FeatureTitle", "Bidding Phase")]
        [Xunit.TraitAttribute("Description", "Next card starts with player to the right of previous starter")]
        public async System.Threading.Tasks.Task NextCardStartsWithPlayerToTheRightOfPreviousStarter()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Next card starts with player to the right of previous starter", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 80
    await testRunner.GivenAsync("\"Atreides\" is first", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 81
    await testRunner.AndAsync("\"Harkonnen\" is second", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
    await testRunner.AndAsync("\"Emperor\" is third", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
    await testRunner.AndAsync("\"Fremen\" is fourth", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
    await testRunner.AndAsync("there are 2 cards up for auction", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
    await testRunner.WhenAsync("the Bidding Phase starts", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
    await testRunner.AndAsync("\"Atreides\" places a bid of 1", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
    await testRunner.AndAsync("\"Harkonnen\" passes", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
    await testRunner.AndAsync("\"Emperor\" passes", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
    await testRunner.AndAsync("\"Fremen\" passes", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
    await testRunner.ThenAsync("card 1 should be sold", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 91
    await testRunner.AndAsync("it should be \"Harkonnen\" turn to bid", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await BiddingPhaseFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await BiddingPhaseFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
