// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuneBot.Specs.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GuildFactionFeature : object, Xunit.IClassFixture<GuildFactionFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Guild.feature"
#line hidden
        
        public GuildFactionFeature(GuildFactionFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Guild Faction", "  In order to profit from the war\n  As the Guild Faction\n  I want to collect paym" +
                    "ents for shipments", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
     await testRunner.GivenAsync("the game is in the \"ShipmentAndMovement\" phase", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Guild receives payments when others ship")]
        [Xunit.TraitAttribute("FeatureTitle", "Guild Faction")]
        [Xunit.TraitAttribute("Description", "Guild receives payments when others ship")]
        public async System.Threading.Tasks.Task GuildReceivesPaymentsWhenOthersShip()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Guild receives payments when others ship", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 10
    await testRunner.GivenAsync("\"Atreides\" has 10 spice", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
    await testRunner.AndAsync("\"Guild\" has 0 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
    await testRunner.AndAsync("\"Atreides\" has 5 forces in reserves", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
    await testRunner.WhenAsync("\"Atreides\" ships 5 forces to \"Basin\" (Sector 8)", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
    await testRunner.ThenAsync("\"Atreides\" should have 0 spice", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
    await testRunner.AndAsync("\"Guild\" should have 10 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Guild pays half for shipment")]
        [Xunit.TraitAttribute("FeatureTitle", "Guild Faction")]
        [Xunit.TraitAttribute("Description", "Guild pays half for shipment")]
        public async System.Threading.Tasks.Task GuildPaysHalfForShipment()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Guild pays half for shipment", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.GivenAsync("\"Guild\" has 10 spice", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.AndAsync("\"Guild\" has 6 forces in reserves", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.WhenAsync("\"Guild\" ships 6 forces to \"Basin\" (Sector 8)", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("\"Guild\" should have 4 spice", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GuildFactionFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GuildFactionFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
