// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuneBot.Specs.Features.Phases
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BattleResolutionFeature : object, Xunit.IClassFixture<BattleResolutionFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Battle.feature"
#line hidden
        
        public BattleResolutionFeature(BattleResolutionFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Phases", "Battle Resolution", "  In order to resolve conflicts\r\n  As a Game Engine\r\n  I want to determine the wi" +
                    "nner of a battle based on leaders, weapons, and defenses", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Basic Battle Winner")]
        [Xunit.TraitAttribute("FeatureTitle", "Battle Resolution")]
        [Xunit.TraitAttribute("Description", "Basic Battle Winner")]
        public async System.Threading.Tasks.Task BasicBattleWinner()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Basic Battle Winner", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("the game is in the \"Battle\" phase", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
                Reqnroll.Table table6 = new Reqnroll.Table(new string[] {
                            "Faction",
                            "Leader",
                            "Strength",
                            "Weapon",
                            "Defense",
                            "Dial"});
                table6.AddRow(new string[] {
                            "Atreides",
                            "Duncan",
                            "5",
                            "None",
                            "None",
                            "1"});
                table6.AddRow(new string[] {
                            "Harkonnen",
                            "Beast",
                            "5",
                            "None",
                            "None",
                            "5"});
#line 8
    await testRunner.GivenAsync("the following factions are in a battle in \"Arrakeen\":", ((string)(null)), table6, "Given ");
#line hidden
#line 12
    await testRunner.WhenAsync("the battle is resolved", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
    await testRunner.ThenAsync("the winner should be \"Harkonnen\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
    await testRunner.AndAsync("\"Atreides\" should lose all forces in \"Arrakeen\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cheap Hero - Win with 0 dial")]
        [Xunit.TraitAttribute("FeatureTitle", "Battle Resolution")]
        [Xunit.TraitAttribute("Description", "Cheap Hero - Win with 0 dial")]
        public async System.Threading.Tasks.Task CheapHero_WinWith0Dial()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Cheap Hero - Win with 0 dial", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
    await testRunner.GivenAsync("the game is in the \"Battle\" phase", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
                Reqnroll.Table table7 = new Reqnroll.Table(new string[] {
                            "Faction",
                            "Leader",
                            "Strength",
                            "Weapon",
                            "Defense",
                            "Dial"});
                table7.AddRow(new string[] {
                            "Atreides",
                            "Duncan",
                            "5",
                            "None",
                            "None",
                            "0"});
                table7.AddRow(new string[] {
                            "Harkonnen",
                            "Feyd-Rautha",
                            "5",
                            "None",
                            "None",
                            "5"});
#line 18
    await testRunner.GivenAsync("the following factions are in a battle in \"Carthag\":", ((string)(null)), table7, "Given ");
#line hidden
#line 22
    await testRunner.WhenAsync("the battle is resolved", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
    await testRunner.ThenAsync("the winner should be \"Atreides\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 24
    await testRunner.AndAsync("\"Duncan\" should be in dead leaders for \"Atreides\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.AndAsync("\"Atreides\" should have won with 0 force loss", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Both players use Cheap Hero - Tie")]
        [Xunit.TraitAttribute("FeatureTitle", "Battle Resolution")]
        [Xunit.TraitAttribute("Description", "Both players use Cheap Hero - Tie")]
        public async System.Threading.Tasks.Task BothPlayersUseCheapHero_Tie()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Both players use Cheap Hero - Tie", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
    await testRunner.GivenAsync("the game is in the \"Battle\" phase", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
                Reqnroll.Table table8 = new Reqnroll.Table(new string[] {
                            "Faction",
                            "Leader",
                            "Strength",
                            "Weapon",
                            "Defense",
                            "Dial"});
                table8.AddRow(new string[] {
                            "Guild",
                            "Guild Representative",
                            "5",
                            "None",
                            "None",
                            "0"});
                table8.AddRow(new string[] {
                            "Emperor",
                            "Bashar",
                            "5",
                            "None",
                            "None",
                            "0"});
#line 29
    await testRunner.GivenAsync("the following factions are in a battle in \"Old Gap\":", ((string)(null)), table8, "Given ");
#line hidden
#line 33
    await testRunner.WhenAsync("the battle is resolved", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.ThenAsync("the battle should result in a tie", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
    await testRunner.AndAsync("\"Guild Representative\" should be in dead leaders for \"Guild\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync("\"Bashar\" should be in dead leaders for \"Emperor\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cheap Hero overrides normal strength")]
        [Xunit.TraitAttribute("FeatureTitle", "Battle Resolution")]
        [Xunit.TraitAttribute("Description", "Cheap Hero overrides normal strength")]
        public async System.Threading.Tasks.Task CheapHeroOverridesNormalStrength()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Cheap Hero overrides normal strength", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync("the game is in the \"Battle\" phase", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
                Reqnroll.Table table9 = new Reqnroll.Table(new string[] {
                            "Faction",
                            "Leader",
                            "Strength",
                            "Weapon",
                            "Defense",
                            "Dial"});
                table9.AddRow(new string[] {
                            "Fremen",
                            "Stilgar",
                            "5",
                            "None",
                            "None",
                            "0"});
                table9.AddRow(new string[] {
                            "Atreides",
                            "Duncan",
                            "5",
                            "None",
                            "None",
                            "10"});
#line 40
    await testRunner.GivenAsync("the following factions are in a battle in \"Arrakeen\":", ((string)(null)), table9, "Given ");
#line hidden
#line 44
    await testRunner.WhenAsync("the battle is resolved", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("the winner should be \"Fremen\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
    await testRunner.AndAsync("\"Stilgar\" should be in dead leaders for \"Fremen\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lasgun vs Shield - Atomic Explosion (Attacker Lasgun)")]
        [Xunit.TraitAttribute("FeatureTitle", "Battle Resolution")]
        [Xunit.TraitAttribute("Description", "Lasgun vs Shield - Atomic Explosion (Attacker Lasgun)")]
        public async System.Threading.Tasks.Task LasgunVsShield_AtomicExplosionAttackerLasgun()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Lasgun vs Shield - Atomic Explosion (Attacker Lasgun)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
    await testRunner.GivenAsync("the game is in the \"Battle\" phase", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
                Reqnroll.Table table10 = new Reqnroll.Table(new string[] {
                            "Faction",
                            "Leader",
                            "Strength",
                            "Weapon",
                            "Defense",
                            "Dial"});
                table10.AddRow(new string[] {
                            "Atreides",
                            "Duncan",
                            "5",
                            "Lasgun",
                            "None",
                            "5"});
                table10.AddRow(new string[] {
                            "Harkonnen",
                            "Beast",
                            "5",
                            "None",
                            "Shield",
                            "5"});
#line 50
    await testRunner.GivenAsync("the following factions are in a battle in \"Arrakeen\":", ((string)(null)), table10, "Given ");
#line hidden
#line 54
    await testRunner.WhenAsync("the battle is resolved", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
    await testRunner.ThenAsync("the battle should result in a tie", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
    await testRunner.AndAsync("\"Duncan\" should be in dead leaders for \"Atreides\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.AndAsync("\"Beast\" should be in dead leaders for \"Harkonnen\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
    await testRunner.AndAsync("\"Atreides\" should lose all forces in \"Arrakeen\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.AndAsync("\"Harkonnen\" should lose all forces in \"Arrakeen\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Lasgun vs Shield - Atomic Explosion (Defender Lasgun)")]
        [Xunit.TraitAttribute("FeatureTitle", "Battle Resolution")]
        [Xunit.TraitAttribute("Description", "Lasgun vs Shield - Atomic Explosion (Defender Lasgun)")]
        public async System.Threading.Tasks.Task LasgunVsShield_AtomicExplosionDefenderLasgun()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Lasgun vs Shield - Atomic Explosion (Defender Lasgun)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 62
    await testRunner.GivenAsync("the game is in the \"Battle\" phase", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
                Reqnroll.Table table11 = new Reqnroll.Table(new string[] {
                            "Faction",
                            "Leader",
                            "Strength",
                            "Weapon",
                            "Defense",
                            "Dial"});
                table11.AddRow(new string[] {
                            "Atreides",
                            "Duncan",
                            "5",
                            "None",
                            "Shield",
                            "5"});
                table11.AddRow(new string[] {
                            "Harkonnen",
                            "Beast",
                            "5",
                            "Lasgun",
                            "None",
                            "5"});
#line 63
    await testRunner.GivenAsync("the following factions are in a battle in \"Carthag\":", ((string)(null)), table11, "Given ");
#line hidden
#line 67
    await testRunner.WhenAsync("the battle is resolved", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 68
    await testRunner.ThenAsync("the battle should result in a tie", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 69
    await testRunner.AndAsync("\"Duncan\" should be in dead leaders for \"Atreides\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.AndAsync("\"Beast\" should be in dead leaders for \"Harkonnen\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
    await testRunner.AndAsync("\"Atreides\" should lose all forces in \"Carthag\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
    await testRunner.AndAsync("\"Harkonnen\" should lose all forces in \"Carthag\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await BattleResolutionFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await BattleResolutionFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
