// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuneBot.Specs.Features.Phases
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MovementPhaseFeature : object, Xunit.IClassFixture<MovementPhaseFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Movement.feature"
#line hidden
        
        public MovementPhaseFeature(MovementPhaseFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Phases", "Movement Phase", "  In order to conquer Arrakis\n  As a Player\n  I want to move my forces between te" +
                    "rritories", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
     await testRunner.GivenAsync("the game is in the \"ShipmentAndMovement\" phase", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Move to adjacent territory (Distance 1)")]
        [Xunit.TraitAttribute("FeatureTitle", "Movement Phase")]
        [Xunit.TraitAttribute("Description", "Move to adjacent territory (Distance 1)")]
        public async System.Threading.Tasks.Task MoveToAdjacentTerritoryDistance1()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Move to adjacent territory (Distance 1)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 10
    await testRunner.GivenAsync("\"Atreides\" has 10 forces in \"Arrakeen\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
    await testRunner.WhenAsync("\"Atreides\" moves 5 forces from \"Arrakeen\" to \"Imperial Basin (S3)\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.ThenAsync("\"Atreides\" should have 5 forces in \"Arrakeen\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
    await testRunner.AndAsync("\"Atreides\" should have 5 forces in \"Imperial Basin (S3)\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Move 2 spaces with Ornithopters (Control Arrakeen)")]
        [Xunit.TraitAttribute("FeatureTitle", "Movement Phase")]
        [Xunit.TraitAttribute("Description", "Move 2 spaces with Ornithopters (Control Arrakeen)")]
        public async System.Threading.Tasks.Task Move2SpacesWithOrnithoptersControlArrakeen()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Move 2 spaces with Ornithopters (Control Arrakeen)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 16
    await testRunner.GivenAsync("\"Atreides\" has 10 forces in \"Arrakeen\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
    await testRunner.WhenAsync("\"Atreides\" moves 5 forces from \"Arrakeen\" to \"Imperial Basin (S1)\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
    await testRunner.ThenAsync("\"Atreides\" should have 5 forces in \"Imperial Basin (S1)\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Move 2 spaces without Ornithopters (Fail)")]
        [Xunit.TraitAttribute("FeatureTitle", "Movement Phase")]
        [Xunit.TraitAttribute("Description", "Move 2 spaces without Ornithopters (Fail)")]
        public async System.Threading.Tasks.Task Move2SpacesWithoutOrnithoptersFail()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Move 2 spaces without Ornithopters (Fail)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 23
    await testRunner.GivenAsync("\"Atreides\" has 10 forces in \"Sietch Tabr\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
    await testRunner.WhenAsync("\"Atreides\" moves 5 forces from \"Sietch Tabr\" to \"Imperial Basin (S1)\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("the action should fail with message \"Destination unreachable\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Fremen move 2 spaces without Ornithopters (Pass)")]
        [Xunit.TraitAttribute("FeatureTitle", "Movement Phase")]
        [Xunit.TraitAttribute("Description", "Fremen move 2 spaces without Ornithopters (Pass)")]
        public async System.Threading.Tasks.Task FremenMove2SpacesWithoutOrnithoptersPass()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Fremen move 2 spaces without Ornithopters (Pass)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.GivenAsync("\"Fremen\" has 10 forces in \"Sietch Tabr\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.WhenAsync("\"Fremen\" moves 5 forces from \"Sietch Tabr\" to \"Imperial Basin (S1)\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("\"Fremen\" should have 5 forces in \"Imperial Basin (S1)\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot move into Storm")]
        [Xunit.TraitAttribute("FeatureTitle", "Movement Phase")]
        [Xunit.TraitAttribute("Description", "Cannot move into Storm")]
        public async System.Threading.Tasks.Task CannotMoveIntoStorm()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Cannot move into Storm", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.GivenAsync("\"Atreides\" has 10 forces in \"Arrakeen\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.AndAsync("the storm is at sector 2", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.WhenAsync("\"Atreides\" moves 5 forces from \"Arrakeen\" to \"Imperial Basin (S2)\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
    await testRunner.ThenAsync("the action should fail with message \"Cannot move through Storm\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot move twice in same turn")]
        [Xunit.TraitAttribute("FeatureTitle", "Movement Phase")]
        [Xunit.TraitAttribute("Description", "Cannot move twice in same turn")]
        public async System.Threading.Tasks.Task CannotMoveTwiceInSameTurn()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Cannot move twice in same turn", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 44
    await testRunner.GivenAsync("\"Atreides\" has 10 forces in \"Arrakeen\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
    await testRunner.AndAsync("\"Atreides\" has 5 forces in \"Imperial Basin (S3)\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
    await testRunner.WhenAsync("\"Atreides\" moves 5 forces from \"Arrakeen\" to \"Imperial Basin (S3)\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
    await testRunner.AndAsync("\"Atreides\" moves 3 forces from \"Imperial Basin (S3)\" to \"Old Gap\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.ThenAsync("the action should fail with message \"have already moved\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot move 0 forces")]
        [Xunit.TraitAttribute("FeatureTitle", "Movement Phase")]
        [Xunit.TraitAttribute("Description", "Cannot move 0 forces")]
        public async System.Threading.Tasks.Task CannotMove0Forces()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Cannot move 0 forces", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 51
    await testRunner.GivenAsync("\"Atreides\" has 10 forces in \"Arrakeen\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
    await testRunner.WhenAsync("\"Atreides\" moves 0 forces from \"Arrakeen\" to \"Imperial Basin (S3)\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
    await testRunner.ThenAsync("the action should fail with message \"Amount must be positive\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await MovementPhaseFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await MovementPhaseFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
