// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuneBot.Specs.Features.Phases
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SpiceCollectionPhaseFeature : object, Xunit.IClassFixture<SpiceCollectionPhaseFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SpiceCollection.feature"
#line hidden
        
        public SpiceCollectionPhaseFeature(SpiceCollectionPhaseFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Phases", "Spice Collection Phase", "  In order to harvest spice from territories\r\n  As a Player\r\n  I want to collect " +
                    "spice from territories I control", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
     await testRunner.GivenAsync("the game is in the \"SpiceCollection\" phase", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Collect spice from uncontested territory")]
        [Xunit.TraitAttribute("FeatureTitle", "Spice Collection Phase")]
        [Xunit.TraitAttribute("Description", "Collect spice from uncontested territory")]
        public async System.Threading.Tasks.Task CollectSpiceFromUncontestedTerritory()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Collect spice from uncontested territory", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 10
    await testRunner.GivenAsync("\"Atreides\" has 5 forces in \"The Great Flat\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
    await testRunner.AndAsync("territory \"The Great Flat\" contains 10 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
    await testRunner.WhenAsync("spice collection is resolved", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
    await testRunner.ThenAsync("\"Atreides\" should have 10 spice", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
    await testRunner.AndAsync("\"The Great Flat\" should have 0 spice remaining", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Partial spice collection when not enough spice")]
        [Xunit.TraitAttribute("FeatureTitle", "Spice Collection Phase")]
        [Xunit.TraitAttribute("Description", "Partial spice collection when not enough spice")]
        public async System.Threading.Tasks.Task PartialSpiceCollectionWhenNotEnoughSpice()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Partial spice collection when not enough spice", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 18
    await testRunner.GivenAsync("\"Harkonnen\" has 10 forces in \"Broken Land\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
    await testRunner.AndAsync("territory \"Broken Land\" contains 6 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.WhenAsync("spice collection is resolved", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.ThenAsync("\"Harkonnen\" should have 6 spice", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
    await testRunner.AndAsync("\"Broken Land\" should have 0 spice remaining", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="No collection from contested territory")]
        [Xunit.TraitAttribute("FeatureTitle", "Spice Collection Phase")]
        [Xunit.TraitAttribute("Description", "No collection from contested territory")]
        public async System.Threading.Tasks.Task NoCollectionFromContestedTerritory()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("No collection from contested territory", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.GivenAsync("\"Atreides\" has 5 forces in \"Red Chasm\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
    await testRunner.AndAsync("\"Harkonnen\" has 3 forces in \"Red Chasm\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
    await testRunner.AndAsync("territory \"Red Chasm\" contains 10 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
    await testRunner.WhenAsync("spice collection is resolved", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
    await testRunner.ThenAsync("\"Atreides\" should have 0 spice", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
    await testRunner.AndAsync("\"Harkonnen\" should have 0 spice", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync("\"Red Chasm\" should have 10 spice remaining", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SpiceCollectionPhaseFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SpiceCollectionPhaseFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
