// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuneBot.Specs.Features.Factions
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AtreidesPrescienceInBattleFeature : object, Xunit.IClassFixture<AtreidesPrescienceInBattleFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Prescience.feature"
#line hidden
        
        public AtreidesPrescienceInBattleFeature(AtreidesPrescienceInBattleFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Factions", "Atreides Prescience in Battle", "  In order to gain advantage in combat\r\n  As Atreides\r\n  I want to see opponent\'s" +
                    " battle plan elements", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
     await testRunner.GivenAsync("the game is in the \"Battle\" phase", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
     await testRunner.AndAsync("there is an active battle in \"Arrakeen\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atreides reveals opponent\'s leader")]
        [Xunit.TraitAttribute("FeatureTitle", "Atreides Prescience in Battle")]
        [Xunit.TraitAttribute("Description", "Atreides reveals opponent\'s leader")]
        public async System.Threading.Tasks.Task AtreidesRevealsOpponentsLeader()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Atreides reveals opponent\'s leader", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 11
    await testRunner.GivenAsync("\"Atreides\" is in the battle", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
    await testRunner.AndAsync("\"Harkonnen\" is in the battle", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
    await testRunner.WhenAsync("\"Atreides\" uses Prescience to reveal \"Leader\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
    await testRunner.AndAsync("\"Harkonnen\" submits battle plan with leader \"Feyd-Rautha\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.ThenAsync("\"Atreides\" should receive DM revealing \"Feyd-Rautha\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atreides reveals opponent\'s dial")]
        [Xunit.TraitAttribute("FeatureTitle", "Atreides Prescience in Battle")]
        [Xunit.TraitAttribute("Description", "Atreides reveals opponent\'s dial")]
        public async System.Threading.Tasks.Task AtreidesRevealsOpponentsDial()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Atreides reveals opponent\'s dial", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 18
    await testRunner.GivenAsync("\"Atreides\" is in the battle", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
    await testRunner.AndAsync("\"Fremen\" is in the battle", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.WhenAsync("\"Atreides\" uses Prescience to reveal \"Dial\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.AndAsync("\"Fremen\" submits battle plan with dial 7", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.ThenAsync("\"Atreides\" should receive DM revealing \"7\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atreides reveals opponent\'s weapon")]
        [Xunit.TraitAttribute("FeatureTitle", "Atreides Prescience in Battle")]
        [Xunit.TraitAttribute("Description", "Atreides reveals opponent\'s weapon")]
        public async System.Threading.Tasks.Task AtreidesRevealsOpponentsWeapon()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Atreides reveals opponent\'s weapon", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.GivenAsync("\"Atreides\" is in the battle", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
    await testRunner.AndAsync("\"Guild\" is in the battle", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.WhenAsync("\"Atreides\" uses Prescience to reveal \"Weapon\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
    await testRunner.AndAsync("\"Guild\" submits battle plan with weapon \"Lasgun\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
    await testRunner.ThenAsync("\"Atreides\" should receive DM revealing \"Lasgun\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atreides reveals opponent\'s defense")]
        [Xunit.TraitAttribute("FeatureTitle", "Atreides Prescience in Battle")]
        [Xunit.TraitAttribute("Description", "Atreides reveals opponent\'s defense")]
        public async System.Threading.Tasks.Task AtreidesRevealsOpponentsDefense()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Atreides reveals opponent\'s defense", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 32
    await testRunner.GivenAsync("\"Atreides\" is in the battle", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 33
    await testRunner.AndAsync("\"Emperor\" is in the battle", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.WhenAsync("\"Atreides\" uses Prescience to reveal \"Defense\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
    await testRunner.AndAsync("\"Emperor\" submits battle plan with defense \"Shield\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.ThenAsync("\"Atreides\" should receive DM revealing \"Shield\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot use Prescience twice in same battle")]
        [Xunit.TraitAttribute("FeatureTitle", "Atreides Prescience in Battle")]
        [Xunit.TraitAttribute("Description", "Cannot use Prescience twice in same battle")]
        public async System.Threading.Tasks.Task CannotUsePrescienceTwiceInSameBattle()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Cannot use Prescience twice in same battle", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 39
    await testRunner.GivenAsync("\"Atreides\" is in the battle", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
    await testRunner.AndAsync("\"Harkonnen\" is in the battle", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.WhenAsync("\"Atreides\" uses Prescience to reveal \"Leader\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.AndAsync("\"Atreides\" uses Prescience to reveal \"Dial\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
    await testRunner.ThenAsync("the action should fail with message \"Prescience already used\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Only Atreides can use Prescience")]
        [Xunit.TraitAttribute("FeatureTitle", "Atreides Prescience in Battle")]
        [Xunit.TraitAttribute("Description", "Only Atreides can use Prescience")]
        public async System.Threading.Tasks.Task OnlyAtreidesCanUsePrescience()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Only Atreides can use Prescience", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 45
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 46
    await testRunner.GivenAsync("\"Harkonnen\" is in the battle", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
    await testRunner.AndAsync("\"Atreides\" is in the battle", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.WhenAsync("\"Harkonnen\" uses Prescience to reveal \"Leader\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
    await testRunner.ThenAsync("the action should fail with message \"Only Atreides can use Prescience\"", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AtreidesPrescienceInBattleFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AtreidesPrescienceInBattleFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
